# substitutions can be overridden during build:
# $_REGION: Region for Artifact Registry and Cloud Run
# $_SERVICE_NAME: Name of the Cloud Run service
# $_REPOSITORY: Name of the Artifact Registry repository
# $_TAG: Docker image tag (defaults to latest)
# $_MIN_INSTANCES: Minimum number of instances (defaults to 0)
# $_MAX_INSTANCES: Maximum number of instances (defaults to 10)
# $_MEMORY: Memory allocation (defaults to 2Gi)
# $_CPU: CPU allocation (defaults to 1)
# $_PORT: Container port (defaults to 8080)
# $_TIMEOUT: Request timeout in seconds (defaults to 300)
# $_MAX_REQUESTS_PER_WORKER: Maximum requests per worker before restart (defaults to 50)
# $_WORKERS: Number of worker processes per instance (defaults to 4)
# $_PROXY_SERVER: Proxy server address (optional)
# $_PROXY_PORT: Proxy server port (optional)
# $_PROXY_USERNAME: Proxy server username (optional)
# $_PROXY_PASSWORD: Proxy server password (optional)
# $_USE_POPUP_BLOCKER: Enable/disable popup blocker extension (defaults to true)
# $_USE_COOKIE_BLOCKER: Enable/disable cookie consent blocker extension (defaults to true)
# $_RATE_LIMIT_ENABLED: Enable/disable rate limiting (defaults to false)
# $_RATE_LIMIT_CAPTURE: Rate limit for capture endpoint (defaults to "1 per second")
# $_RATE_LIMIT_SIGNED: Rate limit for signed URLs (defaults to "5 per second")
# $_AUTH_TOKEN: Authentication token for bearer auth and signed URLs
# $_CACHE_MAX_SIZE: Maximum size for response caching (defaults to 0, disabled)

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}'
      - '--build-arg'
      - 'PORT=${_PORT}'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--port'
      - '${_PORT}'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--set-env-vars'
      - 'CLOUD_RUN=true,AUTH_TOKEN=${_AUTH_TOKEN},MAX_REQUESTS=${_MAX_REQUESTS_PER_WORKER},WORKERS=${_WORKERS},PROXY_SERVER=${_PROXY_SERVER},PROXY_PORT=${_PROXY_PORT},PROXY_USERNAME=${_PROXY_USERNAME},PROXY_PASSWORD=${_PROXY_PASSWORD},USE_POPUP_BLOCKER=${_USE_POPUP_BLOCKER},USE_COOKIE_BLOCKER=${_USE_COOKIE_BLOCKER},RATE_LIMIT_ENABLED=${_RATE_LIMIT_ENABLED},RATE_LIMIT_CAPTURE=${_RATE_LIMIT_CAPTURE},RATE_LIMIT_SIGNED=${_RATE_LIMIT_SIGNED},CACHE_MAX_SIZE=${_CACHE_MAX_SIZE}'
      - '--allow-unauthenticated'

  # Add IAM policy binding to allow unauthenticated access
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - '${_SERVICE_NAME}'
      - '--region=${_REGION}'
      - '--member=allUsers'
      - '--role=roles/run.invoker'

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: pixashot
  _REPOSITORY: pixashot-repo
  _TAG: latest
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "10"
  _MEMORY: "2Gi"
  _CPU: "1"
  _PORT: "8080"
  _TIMEOUT: "300"
  _MAX_REQUESTS_PER_WORKER: "50"
  _WORKERS: "2"
  _AUTH_TOKEN: ""
  _PROXY_SERVER: ""
  _PROXY_PORT: ""
  _PROXY_USERNAME: ""
  _PROXY_PASSWORD: ""
  _USE_POPUP_BLOCKER: "true"
  _USE_COOKIE_BLOCKER: "true"
  _RATE_LIMIT_ENABLED: "false"
  _RATE_LIMIT_CAPTURE: "1 per second"
  _RATE_LIMIT_SIGNED: "5 per second"
  _CACHE_MAX_SIZE: "0"

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'