# substitutions can be overridden during build:
# $_REGION: Region for Artifact Registry and Cloud Run
# $_SERVICE_NAME: Name of the Cloud Run service
# $_REPOSITORY: Name of the Artifact Registry repository
# $_TAG: Docker image tag (defaults to latest)
# $_MIN_INSTANCES: Minimum number of instances (defaults to 0)
# $_MAX_INSTANCES: Maximum number of instances (defaults to 10)
# $_MEMORY: Memory allocation (defaults to 2Gi)
# $_CPU: CPU allocation (defaults to 1)
# $_PORT: Container port (defaults to 8080)
# $_TIMEOUT: Request timeout in seconds (defaults to 300)
# $_ENV_VARS: Environment variables to set in Cloud Run
# $_BROWSER_MAX_CONTEXTS: Maximum number of browser contexts to maintain
# $_BROWSER_CONTEXT_TIMEOUT: Timeout for browser contexts in seconds
# $_BROWSER_MEMORY_LIMIT_MB: Memory limit in MB before context cleanup
# $_AUTH_TOKEN: Authentication token for the service

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}'
      - '--build-arg'
      - 'PORT=${_PORT}'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--port'
      - '${_PORT}'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--set-env-vars'
      - 'CLOUD_RUN=true,BROWSER_MAX_CONTEXTS=${_BROWSER_MAX_CONTEXTS},BROWSER_CONTEXT_TIMEOUT=${_BROWSER_CONTEXT_TIMEOUT},BROWSER_MEMORY_LIMIT_MB=${_BROWSER_MEMORY_LIMIT_MB},AUTH_TOKEN=${_AUTH_TOKEN}'
      - '--allow-unauthenticated'

  # Add IAM policy binding to allow unauthenticated access
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - '${_SERVICE_NAME}'
      - '--region=${_REGION}'
      - '--member=allUsers'
      - '--role=roles/run.invoker'

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: pixashot
  _REPOSITORY: pixashot-repo
  _TAG: latest
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "10"
  _MEMORY: "2Gi"
  _CPU: "1"
  _PORT: "8080"
  _TIMEOUT: "300"
  _BROWSER_MAX_CONTEXTS: "15"
  _BROWSER_CONTEXT_TIMEOUT: "300"
  _BROWSER_MEMORY_LIMIT_MB: "1500"
  _AUTH_TOKEN: ""

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_TAG}'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'